baseurl = "http://sergeyz.spb.ru/"
title = "sz sw dev blog"

theme = "hugo-natrium-theme"

languageCode = "en-us"
preserveTaxonomyNames = true
rssLimit = 10
paginate = 10
pygmentsCodefences = true
pygmentsStyle = "native"

[taxonomies]
    category = "categories"  
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110
    
[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = -120

[[menu.main]]
    name = "Categories"
    url = "/categories"
    weight = -130

[[menu.main]]
    name = "SWA Reading List"
    url = "/swa-reading-list"
    weight = -150

[params]
    description = "Software development blog by sergeyz"

    [params.logo]
    url = "logo.png"
    width = 350
    height = 50
    alt = "Logo"
